# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- main
- feature/demo1

pool:
  vmImage: ubuntu-latest

variables:
  template: 'variables.yml'
  name: 'Angular-$(major).$(minor).$(patch)-$(Build.BuildId)'

stages:
- stage: Build
  displayName: 'Build Stage'
  jobs:
  - job: BuildJob
    displayName: 'Build Job'
    steps:
    # Step 1: Checkout code
    - checkout: self
    # Step 2: Use Node.js version 20.x
    - task: NodeTool@0
      inputs:
        versionSpec: '20.x'
      displayName: 'Install Node.js'
    # Step 4: Lint
    - script: |
      if npm run | grep -q "lint"; then
        npm run lint
      else
        echo "Lint script not found, skipping..."
      fi
     displayName: 'Run lint (if exists)'

    # Step 5: Run unit tests
    - script: |
        npm run test -- --watch=false --browsers=ChromeHeadless
      displayName: 'Run unit tests'
    - script: |
        npm install
        npm run build
      displayName: 'npm install and build'


- stage: Publish
  displayName: 'Publish Stage'
  dependsOn: Build
  condition: succeeded()
  jobs:
  - job: Publish
    displayName: 'Publish Job'
    steps:
    - task: PublishPipelineArtifact@1
      inputs:
        targetPath: '$(Pipeline.Workspace)'
        artifact: 'angular-app'
        publishLocation: 'pipeline'